### ISSUE TITLE
Hitting firewall for no apparent reason

### ISSUE THREAD

**Issue by savchenko** [ivanstan/tle-api#230]
While testing endpoint manually, well under 1 req/sec:

> Vaša konekcija ka ovom serveru je blokirana na firewall-u.

[Documentation](https://tle.ivanstanojevic.me/#docs) does not mention authentication. Is there some further backend heuristic that decides if request should be answered?

**Comment by ivanstan** [comment]
Thanks for reaching out, 
We have request limiter on all of our API endpoints set to 500 request in a timeframe of 60 minutes. Limit is set by client's IP address. If you are predicting satellite state vectors in certain timeframe, please cache data retrieved from us instead of making successive requests. I'd recommend cache time for `/api/tle` and `/api/tle/{satelliteId}` endpoints to be 360 minutes.

There is no other additional authentication required and we will NEVER require one.
